### ISSUE TITLE
Dataset link error

### ISSUE THREAD

**Issue by ninfueng** [SNBQT/Limited-Data-Rolling-Bearing-Fault-Diagnosis-with-Few-shot-Learning#3]
Hello there,

I think your dataset link in `metadata.txt` is old now. The domain of the CWRU dataset is changed from
`http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/` to `https://engineering.case.edu/sites/default/files/`.
I think you can update them by just searching and replacing `http://csegroups.case.edu/sites/default/files/bearingdatacenter/files/Datafiles/` with `https://engineering.case.edu/sites/default/files/` in the `metadata.txt`.

Thank you.

**Comment by SNBQT** [comment]
Thanks your fix. But current  dataset link which you given is not working now. We can download manually from [[Datasets.zip (229MB)]](https://1drv.ms/u/s!At5AiOeueyrEgyUY038Ln_SQ8SRo?e=Fp9o7P) or [提取码: 7uu9](https://pan.baidu.com/s/1WgJMPSDcipugR1Bh4KRadg).
