### ISSUE TITLE
How get the tmp by running the code???

### ISSUE THREAD

**Issue by Chris-G-X** [SNBQT/Limited-Data-Rolling-Bearing-Fault-Diagnosis-with-Few-shot-Learning#5]
How get the tmp by running the code???

**Comment by SNBQT** [comment]
tmp: Save trained models and test results. tmp data is not required to download for running the code.  You can download Datasets manually from [[Datasets.zip (229MB)]](https://1drv.ms/u/s!At5AiOeueyrEgyUY038Ln_SQ8SRo?e=Fp9o7P) or [提取码: 7uu9](https://pan.baidu.com/s/1WgJMPSDcipugR1Bh4KRadg).
